# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Conseiller', 'Conseiller'), ('Courtier', 'Courtier'), ('Administrateur', 'Administrateur')], max_length=100, null=True, verbose_name='Role'),
        ),
    ]
