# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courtier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_courtier', models.CharField(max_length=255)),
                ('cabinet_name', models.CharField(max_length=255)),
                ('orias_code', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=255)),
                ('bic', models.CharField(max_length=255)),
                ('director_firstname', models.CharField(max_length=255)),
                ('director_lastname', models.CharField(max_length=255)),
                ('director_emailaddress', models.CharField(max_length=255)),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspector_phonenumber', models.CharField(max_length=255)),
                ('inspector_emailaddress', models.CharField(max_length=255)),
            ],
        ),
    ]
